In [49]:
import tensorflow as tf
import csv

In [50]:
#Read Data 
def readData(file):
    lines = []
    with open(file) as csvfile:
        reader = csv.reader(csvfile)
        for line in reader:
            lines.append(line)
    return lines

In [51]:
training_data = readData("train.csv")
training_data

[['PassengerId',
  'Survived',
  'Pclass',
  'Name',
  'Sex',
  'Age',
  'SibSp',
  'Parch',
  'Ticket',
  'Fare',
  'Cabin',
  'Embarked'],
 ['1',
  '0',
  '3',
  'Braund, Mr. Owen Harris',
  'male',
  '22',
  '1',
  '0',
  'A/5 21171',
  '7.25',
  '',
  'S'],
 ['2',
  '1',
  '1',
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  '38',
  '1',
  '0',
  'PC 17599',
  '71.2833',
  'C85',
  'C'],
 ['3',
  '1',
  '3',
  'Heikkinen, Miss. Laina',
  'female',
  '26',
  '0',
  '0',
  'STON/O2. 3101282',
  '7.925',
  '',
  'S'],
 ['4',
  '1',
  '1',
  'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'female',
  '35',
  '1',
  '0',
  '113803',
  '53.1',
  'C123',
  'S'],
 ['5',
  '0',
  '3',
  'Allen, Mr. William Henry',
  'male',
  '35',
  '0',
  '0',
  '373450',
  '8.05',
  '',
  'S'],
 ['6',
  '0',
  '3',
  'Moran, Mr. James',
  'male',
  '',
  '0',
  '0',
  '330877',
  '8.4583',
  '',
  'Q'],
 ['7',
  '0',
  '1',
  'McCarthy, Mr. Timothy J',
  'male',
  '54',
  '0',
  '0',
  '17463',
  '51.8625',
  'E46',
  'S'],
 ['8',
  '0',
  '3',
  'Palsson, Master. Gosta Leonard',
  'male',
  '2',
  '3',
  '1',
  '349909',
  '21.075',
  '',
  'S'],
 ['9',
  '1',
  '3',
  'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'female',
  '27',
  '0',
  '2',
  '347742',
  '11.1333',
  '',
  'S'],
 ['10',
  '1',
  '2',
  'Nasser, Mrs. Nicholas (Adele Achem)',
  'female',
  '14',
  '1',
  '0',
  '237736',
  '30.0708',
  '',
  'C'],
 ['11',
  '1',
  '3',
  'Sandstrom, Miss. Marguerite Rut',
  'female',
  '4',
  '1',
  '1',
  'PP 9549',
  '16.7',
  'G6',
  'S'],
 ['12',
  '1',
  '1',
  'Bonnell, Miss. Elizabeth',
  'female',
  '58',
  '0',
  '0',
  '113783',
  '26.55',
  'C103',
  'S'],
 ['13',
  '0',
  '3',
  'Saundercock, Mr. William Henry',
  'male',
  '20',
  '0',
  '0',
  'A/5. 2151',
  '8.05',
  '',
  'S'],
 ['14',
  '0',
  '3',
  'Andersson, Mr. Anders Johan',
  'male',
  '39',
  '1',
  '5',
  '347082',
  '31.275',
  '',
  'S'],
 ['15',
  '0',
  '3',
  'Vestrom, Miss. Hulda Amanda Adolfina',
  'female',
  '14',
  '0',
  '0',
  '350406',
  '7.8542',
  '',
  'S'],
 ['16',
  '1',
  '2',
  'Hewlett, Mrs. (Mary D Kingcome) ',
  'female',
  '55',
  '0',
  '0',
  '248706',
  '16',
  '',
  'S'],
 ['17',
  '0',
  '3',
  'Rice, Master. Eugene',
  'male',
  '2',
  '4',
  '1',
  '382652',
  '29.125',
  '',
  'Q'],
 ['18',
  '1',
  '2',
  'Williams, Mr. Charles Eugene',
  'male',
  '',
  '0',
  '0',
  '244373',
  '13',
  '',
  'S'],
 ['19',
  '0',
  '3',
  'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'female',
  '31',
  '1',
  '0',
  '345763',
  '18',
  '',
  'S'],
 ['20',
  '1',
  '3',
  'Masselmani, Mrs. Fatima',
  'female',
  '',
  '0',
  '0',
  '2649',
  '7.225',
  '',
  'C'],
 ['21',
  '0',
  '2',
  'Fynney, Mr. Joseph J',
  'male',
  '35',
  '0',
  '0',
  '239865',
  '26',
  '',
  'S'],
 ['22',
  '1',
  '2',
  'Beesley, Mr. Lawrence',
  'male',
  '34',
  '0',
  '0',
  '248698',
  '13',
  'D56',
  'S'],
 ['23',
  '1',
  '3',
  'McGowan, Miss. Anna "Annie"',
  'female',
  '15',
  '0',
  '0',
  '330923',
  '8.0292',
  '',
  'Q'],
 ['24',
  '1',
  '1',
  'Sloper, Mr. William Thompson',
  'male',
  '28',
  '0',
  '0',
  '113788',
  '35.5',
  'A6',
  'S'],
 ['25',
  '0',
  '3',
  'Palsson, Miss. Torborg Danira',
  'female',
  '8',
  '3',
  '1',
  '349909',
  '21.075',
  '',
  'S'],
 ['26',
  '1',
  '3',
  'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'female',
  '38',
  '1',
  '5',
  '347077',
  '31.3875',
  '',
  'S'],
 ['27',
  '0',
  '3',
  'Emir, Mr. Farred Chehab',
  'male',
  '',
  '0',
  '0',
  '2631',
  '7.225',
  '',
  'C'],
 ['28',
  '0',
  '1',
  'Fortune, Mr. Charles Alexander',
  'male',
  '19',
  '3',
  '2',
  '19950',
  '263',
  'C23 C25 C27',
  'S'],
 ['29',
  '1',
  '3',
  'O\'Dwyer, Miss. Ellen "Nellie"',
  'female',
  '',
  '0',
  '0',
  '330959',
  '7.8792',
  '',
  'Q'],
 ['30',
  '0',
  '3',
  'Todoroff, Mr. Lalio',
  'male',
  '',
  '0',
  '0',
  '349216',
  '7.8958',
  '',
  'S'],
 ['31',
  '0',
  '1',
  'Uruchurtu, Don. Manuel E',
  'male',
  '40',
  '0',
  '0',
  'PC 17601',
  '27.7208',
  '',
  'C'],
 ['32',
  '1',
  '1',
  'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'female',
  '',
  '1',
  '0',
  'PC 17569',
  '146.5208',
  'B78',
  'C'],
 ['33',
  '1',
  '3',
  'Glynn, Miss. Mary Agatha',
  'female',
  '',
  '0',
  '0',
  '335677',
  '7.75',
  '',
  'Q'],
 ['34',
  '0',
  '2',
  'Wheadon, Mr. Edward H',
  'male',
  '66',
  '0',
  '0',
  'C.A. 24579',
  '10.5',
  '',
  'S'],
 ['35',
  '0',
  '1',
  'Meyer, Mr. Edgar Joseph',
  'male',
  '28',
  '1',
  '0',
  'PC 17604',
  '82.1708',
  '',
  'C'],
 ['36',
  '0',
  '1',
  'Holverson, Mr. Alexander Oskar',
  'male',
  '42',
  '1',
  '0',
  '113789',
  '52',
  '',
  'S'],
 ['37',
  '1',
  '3',
  'Mamee, Mr. Hanna',
  'male',
  '',
  '0',
  '0',
  '2677',
  '7.2292',
  '',
  'C'],
 ['38',
  '0',
  '3',
  'Cann, Mr. Ernest Charles',
  'male',
  '21',
  '0',
  '0',
  'A./5. 2152',
  '8.05',
  '',
  'S'],
 ['39',
  '0',
  '3',
  'Vander Planke, Miss. Augusta Maria',
  'female',
  '18',
  '2',
  '0',
  '345764',
  '18',
  '',
  'S'],
 ['40',
  '1',
  '3',
  'Nicola-Yarred, Miss. Jamila',
  'female',
  '14',
  '1',
  '0',
  '2651',
  '11.2417',
  '',
  'C'],
 ['41',
  '0',
  '3',
  'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'female',
  '40',
  '1',
  '0',
  '7546',
  '9.475',
  '',
  'S'],
 ['42',
  '0',
  '2',
  'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'female',
  '27',
  '1',
  '0',
  '11668',
  '21',
  '',
  'S'],
 ['43',
  '0',
  '3',
  'Kraeff, Mr. Theodor',
  'male',
  '',
  '0',
  '0',
  '349253',
  '7.8958',
  '',
  'C'],
 ['44',
  '1',
  '2',
  'Laroche, Miss. Simonne Marie Anne Andree',
  'female',
  '3',
  '1',
  '2',
  'SC/Paris 2123',
  '41.5792',
  '',
  'C'],
 ['45',
  '1',
  '3',
  'Devaney, Miss. Margaret Delia',
  'female',
  '19',
  '0',
  '0',
  '330958',
  '7.8792',
  '',
  'Q'],
 ['46',
  '0',
  '3',
  'Rogers, Mr. William John',
  'male',
  '',
  '0',
  '0',
  'S.C./A.4. 23567',
  '8.05',
  '',
  'S'],
 ['47',
  '0',
  '3',
  'Lennon, Mr. Denis',
  'male',
  '',
  '1',
  '0',
  '370371',
  '15.5',
  '',
  'Q'],
 ['48',
  '1',
  '3',
  "O'Driscoll, Miss. Bridget",
  'female',
  '',
  '0',
  '0',
  '14311',
  '7.75',
  '',
  'Q'],
 ['49',
  '0',
  '3',
  'Samaan, Mr. Youssef',
  'male',
  '',
  '2',
  '0',
  '2662',
  '21.6792',
  '',
  'C'],
 ['50',
  '0',
  '3',
  'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'female',
  '18',
  '1',
  '0',
  '349237',
  '17.8',
  '',
  'S'],
 ['51',
  '0',
  '3',
  'Panula, Master. Juha Niilo',
  'male',
  '7',
  '4',
  '1',
  '3101295',
  '39.6875',
  '',
  'S'],
 ['52',
  '0',
  '3',
  'Nosworthy, Mr. Richard Cater',
  'male',
  '21',
  '0',
  '0',
  'A/4. 39886',
  '7.8',
  '',
  'S'],
 ['53',
  '1',
  '1',
  'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'female',
  '49',
  '1',
  '0',
  'PC 17572',
  '76.7292',
  'D33',
  'C'],
 ['54',
  '1',
  '2',
  'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'female',
  '29',
  '1',
  '0',
  '2926',
  '26',
  '',
  'S'],
 ['55',
  '0',
  '1',
  'Ostby, Mr. Engelhart Cornelius',
  'male',
  '65',
  '0',
  '1',
  '113509',
  '61.9792',
  'B30',
  'C'],
 ['56',
  '1',
  '1',
  'Woolner, Mr. Hugh',
  'male',
  '',
  '0',
  '0',
  '19947',
  '35.5',
  'C52',
  'S'],
 ['57',
  '1',
  '2',
  'Rugg, Miss. Emily',
  'female',
  '21',
  '0',
  '0',
  'C.A. 31026',
  '10.5',
  '',
  'S'],
 ['58',
  '0',
  '3',
  'Novel, Mr. Mansouer',
  'male',
  '28.5',
  '0',
  '0',
  '2697',
  '7.2292',
  '',
  'C'],
 ['59',
  '1',
  '2',
  'West, Miss. Constance Mirium',
  'female',
  '5',
  '1',
  '2',
  'C.A. 34651',
  '27.75',
  '',
  'S'],
 ['60',
  '0',
  '3',
  'Goodwin, Master. William Frederick',
  'male',
  '11',
  '5',
  '2',
  'CA 2144',
  '46.9',
  '',
  'S'],
 ['61',
  '0',
  '3',
  'Sirayanian, Mr. Orsen',
  'male',
  '22',
  '0',
  '0',
  '2669',
  '7.2292',
  '',
  'C'],
 ['62',
  '1',
  '1',
  'Icard, Miss. Amelie',
  'female',
  '38',
  '0',
  '0',
  '113572',
  '80',
  'B28',
  ''],
 ['63',
  '0',
  '1',
  'Harris, Mr. Henry Birkhardt',
  'male',
  '45',
  '1',
  '0',
  '36973',
  '83.475',
  'C83',
  'S'],
 ['64',
  '0',
  '3',
  'Skoog, Master. Harald',
  'male',
  '4',
  '3',
  '2',
  '347088',
  '27.9',
  '',
  'S'],
 ['65',
  '0',
  '1',
  'Stewart, Mr. Albert A',
  'male',
  '',
  '0',
  '0',
  'PC 17605',
  '27.7208',
  '',
  'C'],
 ['66',
  '1',
  '3',
  'Moubarek, Master. Gerios',
  'male',
  '',
  '1',
  '1',
  '2661',
  '15.2458',
  '',
  'C'],
 ['67',
  '1',
  '2',
  'Nye, Mrs. (Elizabeth Ramell)',
  'female',
  '29',
  '0',
  '0',
  'C.A. 29395',
  '10.5',
  'F33',
  'S'],
 ['68',
  '0',
  '3',
  'Crease, Mr. Ernest James',
  'male',
  '19',
  '0',
  '0',
  'S.P. 3464',
  '8.1583',
  '',
  'S'],
 ['69',
  '1',
  '3',
  'Andersson, Miss. Erna Alexandra',
  'female',
  '17',
  '4',
  '2',
  '3101281',
  '7.925',
  '',
  'S'],
 ['70',
  '0',
  '3',
  'Kink, Mr. Vincenz',
  'male',
  '26',
  '2',
  '0',
  '315151',
  '8.6625',
  '',
  'S'],
 ['71',
  '0',
  '2',
  'Jenkin, Mr. Stephen Curnow',
  'male',
  '32',
  '0',
  '0',
  'C.A. 33111',
  '10.5',
  '',
  'S'],
 ['72',
  '0',
  '3',
  'Goodwin, Miss. Lillian Amy',
  'female',
  '16',
  '5',
  '2',
  'CA 2144',
  '46.9',
  '',
  'S'],
 ['73',
  '0',
  '2',
  'Hood, Mr. Ambrose Jr',
  'male',
  '21',
  '0',
  '0',
  'S.O.C. 14879',
  '73.5',
  '',
  'S'],
 ['74',
  '0',
  '3',
  'Chronopoulos, Mr. Apostolos',
  'male',
  '26',
  '1',
  '0',
  '2680',
  '14.4542',
  '',
  'C'],
 ['75',
  '1',
  '3',
  'Bing, Mr. Lee',
  'male',
  '32',
  '0',
  '0',
  '1601',
  '56.4958',
  '',
  'S'],
 ['76',
  '0',
  '3',
  'Moen, Mr. Sigurd Hansen',
  'male',
  '25',
  '0',
  '0',
  '348123',
  '7.65',
  'F G73',
  'S'],
 ['77',
  '0',
  '3',
  'Staneff, Mr. Ivan',
  'male',
  '',
  '0',
  '0',
  '349208',
  '7.8958',
  '',
  'S'],
 ['78',
  '0',
  '3',
  'Moutal, Mr. Rahamin Haim',
  'male',
  '',
  '0',
  '0',
  '374746',
  '8.05',
  '',
  'S'],
 ['79',
  '1',
  '2',
  'Caldwell, Master. Alden Gates',
  'male',
  '0.83',
  '0',
  '2',
  '248738',
  '29',
  '',
  'S'],
 ['80',
  '1',
  '3',
  'Dowdell, Miss. Elizabeth',
  'female',
  '30',
  '0',
  '0',
  '364516',
  '12.475',
  '',
  'S'],
 ['81',
  '0',
  '3',
  'Waelens, Mr. Achille',
  'male',
  '22',
  '0',
  '0',
  '345767',
  '9',
  '',
  'S'],
 ['82',
  '1',
  '3',
  'Sheerlinck, Mr. Jan Baptist',
  'male',
  '29',
  '0',
  '0',
  '345779',
  '9.5',
  '',
  'S'],
 ['83',
  '1',
  '3',
  'McDermott, Miss. Brigdet Delia',
  'female',
  '',
  '0',
  '0',
  '330932',
  '7.7875',
  '',
  'Q'],
 ['84',
  '0',
  '1',
  'Carrau, Mr. Francisco M',
  'male',
  '28',
  '0',
  '0',
  '113059',
  '47.1',
  '',
  'S'],
 ['85',
  '1',
  '2',
  'Ilett, Miss. Bertha',
  'female',
  '17',
  '0',
  '0',
  'SO/C 14885',
  '10.5',
  '',
  'S'],
 ['86',
  '1',
  '3',
  'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
  'female',
  '33',
  '3',
  '0',
  '3101278',
  '15.85',
  '',
  'S'],
 ['87',
  '0',
  '3',
  'Ford, Mr. William Neal',
  'male',
  '16',
  '1',
  '3',
  'W./C. 6608',
  '34.375',
  '',
  'S'],
 ['88',
  '0',
  '3',
  'Slocovski, Mr. Selman Francis',
  'male',
  '',
  '0',
  '0',
  'SOTON/OQ 392086',
  '8.05',
  '',
  'S'],
 ['89',
  '1',
  '1',
  'Fortune, Miss. Mabel Helen',
  'female',
  '23',
  '3',
  '2',
  '19950',
  '263',
  'C23 C25 C27',
  'S'],
 ['90',
  '0',
  '3',
  'Celotti, Mr. Francesco',
  'male',
  '24',
  '0',
  '0',
  '343275',
  '8.05',
  '',
  'S'],
 ['91',
  '0',
  '3',
  'Christmann, Mr. Emil',
  'male',
  '29',
  '0',
  '0',
  '343276',
  '8.05',
  '',
  'S'],
 ['92',
  '0',
  '3',
  'Andreasson, Mr. Paul Edvin',
  'male',
  '20',
  '0',
  '0',
  '347466',
  '7.8542',
  '',
  'S'],
 ['93',
  '0',
  '1',
  'Chaffee, Mr. Herbert Fuller',
  'male',
  '46',
  '1',
  '0',
  'W.E.P. 5734',
  '61.175',
  'E31',
  'S'],
 ['94',
  '0',
  '3',
  'Dean, Mr. Bertram Frank',
  'male',
  '26',
  '1',
  '2',
  'C.A. 2315',
  '20.575',
  '',
  'S'],
 ['95',
  '0',
  '3',
  'Coxon, Mr. Daniel',
  'male',
  '59',
  '0',
  '0',
  '364500',
  '7.25',
  '',
  'S'],
 ['96',
  '0',
  '3',
  'Shorney, Mr. Charles Joseph',
  'male',
  '',
  '0',
  '0',
  '374910',
  '8.05',
  '',
  'S'],
 ['97',
  '0',
  '1',
  'Goldschmidt, Mr. George B',
  'male',
  '71',
  '0',
  '0',
  'PC 17754',
  '34.6542',
  'A5',
  'C'],
 ['98',
  '1',
  '1',
  'Greenfield, Mr. William Bertram',
  'male',
  '23',
  '0',
  '1',
  'PC 17759',
  '63.3583',
  'D10 D12',
  'C'],
 ['99',
  '1',
  '2',
  'Doling, Mrs. John T (Ada Julia Bone)',
  'female',
  '34',
  '0',
  '1',
  '231919',
  '23',
  '',
  'S'],
 ['100',
  '0',
  '2',
  'Kantor, Mr. Sinai',
  'male',
  '34',
  '1',
  '0',
  '244367',
  '26',
  '',
  'S'],
 ['101',
  '0',
  '3',
  'Petranec, Miss. Matilda',
  'female',
  '28',
  '0',
  '0',
  '349245',
  '7.8958',
  '',
  'S'],
 ['102',
  '0',
  '3',
  'Petroff, Mr. Pastcho ("Pentcho")',
  'male',
  '',
  '0',
  '0',
  '349215',
  '7.8958',
  '',
  'S'],
 ['103',
  '0',
  '1',
  'White, Mr. Richard Frasar',
  'male',
  '21',
  '0',
  '1',
  '35281',
  '77.2875',
  'D26',
  'S'],
 ['104',
  '0',
  '3',
  'Johansson, Mr. Gustaf Joel',
  'male',
  '33',
  '0',
  '0',
  '7540',
  '8.6542',
  '',
  'S'],
 ['105',
  '0',
  '3',
  'Gustafsson, Mr. Anders Vilhelm',
  'male',
  '37',
  '2',
  '0',
  '3101276',
  '7.925',
  '',
  'S'],
 ['106',
  '0',
  '3',
  'Mionoff, Mr. Stoytcho',
  'male',
  '28',
  '0',
  '0',
  '349207',
  '7.8958',
  '',
  'S'],
 ['107',
  '1',
  '3',
  'Salkjelsvik, Miss. Anna Kristine',
  'female',
  '21',
  '0',
  '0',
  '343120',
  '7.65',
  '',
  'S'],
 ['108',
  '1',
  '3',
  'Moss, Mr. Albert Johan',
  'male',
  '',
  '0',
  '0',
  '312991',
  '7.775',
  '',
  'S'],
 ['109',
  '0',
  '3',
  'Rekic, Mr. Tido',
  'male',
  '38',
  '0',
  '0',
  '349249',
  '7.8958',
  '',
  'S'],
 ['110',
  '1',
  '3',
  'Moran, Miss. Bertha',
  'female',
  '',
  '1',
  '0',
  '371110',
  '24.15',
  '',
  'Q'],
 ['111',
  '0',
  '1',
  'Porter, Mr. Walter Chamberlain',
  'male',
  '47',
  '0',
  '0',
  '110465',
  '52',
  'C110',
  'S'],
 ['112',
  '0',
  '3',
  'Zabour, Miss. Hileni',
  'female',
  '14.5',
  '1',
  '0',
  '2665',
  '14.4542',
  '',
  'C'],
 ['113',
  '0',
  '3',
  'Barton, Mr. David John',
  'male',
  '22',
  '0',
  '0',
  '324669',
  '8.05',
  '',
  'S'],
 ['114',
  '0',
  '3',
  'Jussila, Miss. Katriina',
  'female',
  '20',
  '1',
  '0',
  '4136',
  '9.825',
  '',
  'S'],
 ['115',
  '0',
  '3',
  'Attalah, Miss. Malake',
  'female',
  '17',
  '0',
  '0',
  '2627',
  '14.4583',
  '',
  'C'],
 ['116',
  '0',
  '3',
  'Pekoniemi, Mr. Edvard',
  'male',
  '21',
  '0',
  '0',
  'STON/O 2. 3101294',
  '7.925',
  '',
  'S'],
 ['117',
  '0',
  '3',
  'Connors, Mr. Patrick',
  'male',
  '70.5',
  '0',
  '0',
  '370369',
  '7.75',
  '',
  'Q'],
 ['118',
  '0',
  '2',
  'Turpin, Mr. William John Robert',
  'male',
  '29',
  '1',
  '0',
  '11668',
  '21',
  '',
  'S'],
 ['119',
  '0',
  '1',
  'Baxter, Mr. Quigg Edmond',
  'male',
  '24',
  '0',
  '1',
  'PC 17558',
  '247.5208',
  'B58 B60',
  'C'],
 ['120',
  '0',
  '3',
  'Andersson, Miss. Ellis Anna Maria',
  'female',
  '2',
  '4',
  '2',
  '347082',
  '31.275',
  '',
  'S'],
 ['121',
  '0',
  '2',
  'Hickman, Mr. Stanley George',
  'male',
  '21',
  '2',
  '0',
  'S.O.C. 14879',
  '73.5',
  '',
  'S'],
 ['122',
  '0',
  '3',
  'Moore, Mr. Leonard Charles',
  'male',
  '',
  '0',
  '0',
  'A4. 54510',
  '8.05',
  '',
  'S'],
 ['123',
  '0',
  '2',
  'Nasser, Mr. Nicholas',
  'male',
  '32.5',
  '1',
  '0',
  '237736',
  '30.0708',
  '',
  'C'],
 ['124',
  '1',
  '2',
  'Webber, Miss. Susan',
  'female',
  '32.5',
  '0',
  '0',
  '27267',
  '13',
  'E101',
  'S'],
 ['125',
  '0',
  '1',
  'White, Mr. Percival Wayland',
  'male',
  '54',
  '0',
  '1',
  '35281',
  '77.2875',
  'D26',
  'S'],
 ['126',
  '1',
  '3',
  'Nicola-Yarred, Master. Elias',
  'male',
  '12',
  '1',
  '0',
  '2651',
  '11.2417',
  '',
  'C'],
 ['127',
  '0',
  '3',
  'McMahon, Mr. Martin',
  'male',
  '',
  '0',
  '0',
  '370372',
  '7.75',
  '',
  'Q'],
 ['128',
  '1',
  '3',
  'Madsen, Mr. Fridtjof Arne',
  'male',
  '24',
  '0',
  '0',
  'C 17369',
  '7.1417',
  '',
  'S'],
 ['129',
  '1',
  '3',
  'Peter, Miss. Anna',
  'female',
  '',
  '1',
  '1',
  '2668',
  '22.3583',
  'F E69',
  'C'],
 ['130',
  '0',
  '3',
  'Ekstrom, Mr. Johan',
  'male',
  '45',
  '0',
  '0',
  '347061',
  '6.975',
  '',
  'S'],
 ['131',
  '0',
  '3',
  'Drazenoic, Mr. Jozef',
  'male',
  '33',
  '0',
  '0',
  '349241',
  '7.8958',
  '',
  'C'],
 ['132',
  '0',
  '3',
  'Coelho, Mr. Domingos Fernandeo',
  'male',
  '20',
  '0',
  '0',
  'SOTON/O.Q. 3101307',
  '7.05',
  '',
  'S'],
 ['133',
  '0',
  '3',
  'Robins, Mrs. Alexander A (Grace Charity Laury)',
  'female',
  '47',
  '1',
  '0',
  'A/5. 3337',
  '14.5',
  '',
  'S'],
 ['134',
  '1',
  '2',
  'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
  'female',
  '29',
  '1',
  '0',
  '228414',
  '26',
  '',
  'S'],
 ['135',
  '0',
  '2',
  'Sobey, Mr. Samuel James Hayden',
  'male',
  '25',
  '0',
  '0',
  'C.A. 29178',
  '13',
  '',
  'S'],
 ['136',
  '0',
  '2',
  'Richard, Mr. Emile',
  'male',
  '23',
  '0',
  '0',
  'SC/PARIS 2133',
  '15.0458',
  '',
  'C'],
 ['137',
  '1',
  '1',
  'Newsom, Miss. Helen Monypeny',
  'female',
  '19',
  '0',
  '2',
  '11752',
  '26.2833',
  'D47',
  'S'],
 ['138',
  '0',
  '1',
  'Futrelle, Mr. Jacques Heath',
  'male',
  '37',
  '1',
  '0',
  '113803',
  '53.1',
  'C123',
  'S'],
 ['139',
  '0',
  '3',
  'Osen, Mr. Olaf Elon',
  'male',
  '16',
  '0',
  '0',
  '7534',
  '9.2167',
  '',
  'S'],
 ['140',
  '0',
  '1',
  'Giglio, Mr. Victor',
  'male',
  '24',
  '0',
  '0',
  'PC 17593',
  '79.2',
  'B86',
  'C'],
 ['141',
  '0',
  '3',
  'Boulos, Mrs. Joseph (Sultana)',
  'female',
  '',
  '0',
  '2',
  '2678',
  '15.2458',
  '',
  'C'],
 ['142',
  '1',
  '3',
  'Nysten, Miss. Anna Sofia',
  'female',
  '22',
  '0',
  '0',
  '347081',
  '7.75',
  '',
  'S'],
 ['143',
  '1',
  '3',
  'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
  'female',
  '24',
  '1',
  '0',
  'STON/O2. 3101279',
  '15.85',
  '',
  'S'],
 ['144',
  '0',
  '3',
  'Burke, Mr. Jeremiah',
  'male',
  '19',
  '0',
  '0',
  '365222',
  '6.75',
  '',
  'Q'],
 ['145',
  '0',
  '2',
  'Andrew, Mr. Edgardo Samuel',
  'male',
  '18',
  '0',
  '0',
  '231945',
  '11.5',
  '',
  'S'],
 ['146',
  '0',
  '2',
  'Nicholls, Mr. Joseph Charles',
  'male',
  '19',
  '1',
  '1',
  'C.A. 33112',
  '36.75',
  '',
  'S'],
 ['147',
  '1',
  '3',
  'Andersson, Mr. August Edvard ("Wennerstrom")',
  'male',
  '27',
  '0',
  '0',
  '350043',
  '7.7958',
  '',
  'S'],
 ['148',
  '0',
  '3',
  'Ford, Miss. Robina Maggie "Ruby"',
  'female',
  '9',
  '2',
  '2',
  'W./C. 6608',
  '34.375',
  '',
  'S'],
 ['149',
  '0',
  '2',
  'Navratil, Mr. Michel ("Louis M Hoffman")',
  'male',
  '36.5',
  '0',
  '2',
  '230080',
  '26',
  'F2',
  'S'],
 ['150',
  '0',
  '2',
  'Byles, Rev. Thomas Roussel Davids',
  'male',
  '42',
  '0',
  '0',
  '244310',
  '13',
  '',
  'S'],
 ['151',
  '0',
  '2',
  'Bateman, Rev. Robert James',
  'male',
  '51',
  '0',
  '0',
  'S.O.P. 1166',
  '12.525',
  '',
  'S'],
 ['152',
  '1',
  '1',
  'Pears, Mrs. Thomas (Edith Wearne)',
  'female',
  '22',
  '1',
  '0',
  '113776',
  '66.6',
  'C2',
  'S'],
 ['153',
  '0',
  '3',
  'Meo, Mr. Alfonzo',
  'male',
  '55.5',
  '0',
  '0',
  'A.5. 11206',
  '8.05',
  '',
  'S'],
 ['154',
  '0',
  '3',
  'van Billiard, Mr. Austin Blyler',
  'male',
  '40.5',
  '0',
  '2',
  'A/5. 851',
  '14.5',
  '',
  'S'],
 ['155',
  '0',
  '3',
  'Olsen, Mr. Ole Martin',
  'male',
  '',
  '0',
  '0',
  'Fa 265302',
  '7.3125',
  '',
  'S'],
 ['156',
  '0',
  '1',
  'Williams, Mr. Charles Duane',
  'male',
  '51',
  '0',
  '1',
  'PC 17597',
  '61.3792',
  '',
  'C'],
 ['157',
  '1',
  '3',
  'Gilnagh, Miss. Katherine "Katie"',
  'female',
  '16',
  '0',
  '0',
  '35851',

In [52]:
type(training_data)

list

In [53]:
headers = training_data[0]
headers

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [54]:
training_data = training_data[1:]

In [55]:
training_data

[['1',
  '0',
  '3',
  'Braund, Mr. Owen Harris',
  'male',
  '22',
  '1',
  '0',
  'A/5 21171',
  '7.25',
  '',
  'S'],
 ['2',
  '1',
  '1',
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  '38',
  '1',
  '0',
  'PC 17599',
  '71.2833',
  'C85',
  'C'],
 ['3',
  '1',
  '3',
  'Heikkinen, Miss. Laina',
  'female',
  '26',
  '0',
  '0',
  'STON/O2. 3101282',
  '7.925',
  '',
  'S'],
 ['4',
  '1',
  '1',
  'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'female',
  '35',
  '1',
  '0',
  '113803',
  '53.1',
  'C123',
  'S'],
 ['5',
  '0',
  '3',
  'Allen, Mr. William Henry',
  'male',
  '35',
  '0',
  '0',
  '373450',
  '8.05',
  '',
  'S'],
 ['6',
  '0',
  '3',
  'Moran, Mr. James',
  'male',
  '',
  '0',
  '0',
  '330877',
  '8.4583',
  '',
  'Q'],
 ['7',
  '0',
  '1',
  'McCarthy, Mr. Timothy J',
  'male',
  '54',
  '0',
  '0',
  '17463',
  '51.8625',
  'E46',
  'S'],
 ['8',
  '0',
  '3',
  'Palsson, Master. Gosta Leonard',
  'male',
  '2',
  '3',
  '1',
  '349909',
  '21.075',
  '',
  'S'],
 ['9',
  '1',
  '3',
  'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'female',
  '27',
  '0',
  '2',
  '347742',
  '11.1333',
  '',
  'S'],
 ['10',
  '1',
  '2',
  'Nasser, Mrs. Nicholas (Adele Achem)',
  'female',
  '14',
  '1',
  '0',
  '237736',
  '30.0708',
  '',
  'C'],
 ['11',
  '1',
  '3',
  'Sandstrom, Miss. Marguerite Rut',
  'female',
  '4',
  '1',
  '1',
  'PP 9549',
  '16.7',
  'G6',
  'S'],
 ['12',
  '1',
  '1',
  'Bonnell, Miss. Elizabeth',
  'female',
  '58',
  '0',
  '0',
  '113783',
  '26.55',
  'C103',
  'S'],
 ['13',
  '0',
  '3',
  'Saundercock, Mr. William Henry',
  'male',
  '20',
  '0',
  '0',
  'A/5. 2151',
  '8.05',
  '',
  'S'],
 ['14',
  '0',
  '3',
  'Andersson, Mr. Anders Johan',
  'male',
  '39',
  '1',
  '5',
  '347082',
  '31.275',
  '',
  'S'],
 ['15',
  '0',
  '3',
  'Vestrom, Miss. Hulda Amanda Adolfina',
  'female',
  '14',
  '0',
  '0',
  '350406',
  '7.8542',
  '',
  'S'],
 ['16',
  '1',
  '2',
  'Hewlett, Mrs. (Mary D Kingcome) ',
  'female',
  '55',
  '0',
  '0',
  '248706',
  '16',
  '',
  'S'],
 ['17',
  '0',
  '3',
  'Rice, Master. Eugene',
  'male',
  '2',
  '4',
  '1',
  '382652',
  '29.125',
  '',
  'Q'],
 ['18',
  '1',
  '2',
  'Williams, Mr. Charles Eugene',
  'male',
  '',
  '0',
  '0',
  '244373',
  '13',
  '',
  'S'],
 ['19',
  '0',
  '3',
  'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'female',
  '31',
  '1',
  '0',
  '345763',
  '18',
  '',
  'S'],
 ['20',
  '1',
  '3',
  'Masselmani, Mrs. Fatima',
  'female',
  '',
  '0',
  '0',
  '2649',
  '7.225',
  '',
  'C'],
 ['21',
  '0',
  '2',
  'Fynney, Mr. Joseph J',
  'male',
  '35',
  '0',
  '0',
  '239865',
  '26',
  '',
  'S'],
 ['22',
  '1',
  '2',
  'Beesley, Mr. Lawrence',
  'male',
  '34',
  '0',
  '0',
  '248698',
  '13',
  'D56',
  'S'],
 ['23',
  '1',
  '3',
  'McGowan, Miss. Anna "Annie"',
  'female',
  '15',
  '0',
  '0',
  '330923',
  '8.0292',
  '',
  'Q'],
 ['24',
  '1',
  '1',
  'Sloper, Mr. William Thompson',
  'male',
  '28',
  '0',
  '0',
  '113788',
  '35.5',
  'A6',
  'S'],
 ['25',
  '0',
  '3',
  'Palsson, Miss. Torborg Danira',
  'female',
  '8',
  '3',
  '1',
  '349909',
  '21.075',
  '',
  'S'],
 ['26',
  '1',
  '3',
  'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'female',
  '38',
  '1',
  '5',
  '347077',
  '31.3875',
  '',
  'S'],
 ['27',
  '0',
  '3',
  'Emir, Mr. Farred Chehab',
  'male',
  '',
  '0',
  '0',
  '2631',
  '7.225',
  '',
  'C'],
 ['28',
  '0',
  '1',
  'Fortune, Mr. Charles Alexander',
  'male',
  '19',
  '3',
  '2',
  '19950',
  '263',
  'C23 C25 C27',
  'S'],
 ['29',
  '1',
  '3',
  'O\'Dwyer, Miss. Ellen "Nellie"',
  'female',
  '',
  '0',
  '0',
  '330959',
  '7.8792',
  '',
  'Q'],
 ['30',
  '0',
  '3',
  'Todoroff, Mr. Lalio',
  'male',
  '',
  '0',
  '0',
  '349216',
  '7.8958',
  '',
  'S'],
 ['31',
  '0',
  '1',
  'Uruchurtu, Don. Manuel E',
  'male',
  '40',
  '0',
  '0',
  'PC 17601',
  '27.7208',
  '',
  'C'],
 ['32',
  '1',
  '1',
  'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'female',
  '',
  '1',
  '0',
  'PC 17569',
  '146.5208',
  'B78',
  'C'],
 ['33',
  '1',
  '3',
  'Glynn, Miss. Mary Agatha',
  'female',
  '',
  '0',
  '0',
  '335677',
  '7.75',
  '',
  'Q'],
 ['34',
  '0',
  '2',
  'Wheadon, Mr. Edward H',
  'male',
  '66',
  '0',
  '0',
  'C.A. 24579',
  '10.5',
  '',
  'S'],
 ['35',
  '0',
  '1',
  'Meyer, Mr. Edgar Joseph',
  'male',
  '28',
  '1',
  '0',
  'PC 17604',
  '82.1708',
  '',
  'C'],
 ['36',
  '0',
  '1',
  'Holverson, Mr. Alexander Oskar',
  'male',
  '42',
  '1',
  '0',
  '113789',
  '52',
  '',
  'S'],
 ['37',
  '1',
  '3',
  'Mamee, Mr. Hanna',
  'male',
  '',
  '0',
  '0',
  '2677',
  '7.2292',
  '',
  'C'],
 ['38',
  '0',
  '3',
  'Cann, Mr. Ernest Charles',
  'male',
  '21',
  '0',
  '0',
  'A./5. 2152',
  '8.05',
  '',
  'S'],
 ['39',
  '0',
  '3',
  'Vander Planke, Miss. Augusta Maria',
  'female',
  '18',
  '2',
  '0',
  '345764',
  '18',
  '',
  'S'],
 ['40',
  '1',
  '3',
  'Nicola-Yarred, Miss. Jamila',
  'female',
  '14',
  '1',
  '0',
  '2651',
  '11.2417',
  '',
  'C'],
 ['41',
  '0',
  '3',
  'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'female',
  '40',
  '1',
  '0',
  '7546',
  '9.475',
  '',
  'S'],
 ['42',
  '0',
  '2',
  'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'female',
  '27',
  '1',
  '0',
  '11668',
  '21',
  '',
  'S'],
 ['43',
  '0',
  '3',
  'Kraeff, Mr. Theodor',
  'male',
  '',
  '0',
  '0',
  '349253',
  '7.8958',
  '',
  'C'],
 ['44',
  '1',
  '2',
  'Laroche, Miss. Simonne Marie Anne Andree',
  'female',
  '3',
  '1',
  '2',
  'SC/Paris 2123',
  '41.5792',
  '',
  'C'],
 ['45',
  '1',
  '3',
  'Devaney, Miss. Margaret Delia',
  'female',
  '19',
  '0',
  '0',
  '330958',
  '7.8792',
  '',
  'Q'],
 ['46',
  '0',
  '3',
  'Rogers, Mr. William John',
  'male',
  '',
  '0',
  '0',
  'S.C./A.4. 23567',
  '8.05',
  '',
  'S'],
 ['47',
  '0',
  '3',
  'Lennon, Mr. Denis',
  'male',
  '',
  '1',
  '0',
  '370371',
  '15.5',
  '',
  'Q'],
 ['48',
  '1',
  '3',
  "O'Driscoll, Miss. Bridget",
  'female',
  '',
  '0',
  '0',
  '14311',
  '7.75',
  '',
  'Q'],
 ['49',
  '0',
  '3',
  'Samaan, Mr. Youssef',
  'male',
  '',
  '2',
  '0',
  '2662',
  '21.6792',
  '',
  'C'],
 ['50',
  '0',
  '3',
  'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'female',
  '18',
  '1',
  '0',
  '349237',
  '17.8',
  '',
  'S'],
 ['51',
  '0',
  '3',
  'Panula, Master. Juha Niilo',
  'male',
  '7',
  '4',
  '1',
  '3101295',
  '39.6875',
  '',
  'S'],
 ['52',
  '0',
  '3',
  'Nosworthy, Mr. Richard Cater',
  'male',
  '21',
  '0',
  '0',
  'A/4. 39886',
  '7.8',
  '',
  'S'],
 ['53',
  '1',
  '1',
  'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'female',
  '49',
  '1',
  '0',
  'PC 17572',
  '76.7292',
  'D33',
  'C'],
 ['54',
  '1',
  '2',
  'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'female',
  '29',
  '1',
  '0',
  '2926',
  '26',
  '',
  'S'],
 ['55',
  '0',
  '1',
  'Ostby, Mr. Engelhart Cornelius',
  'male',
  '65',
  '0',
  '1',
  '113509',
  '61.9792',
  'B30',
  'C'],
 ['56',
  '1',
  '1',
  'Woolner, Mr. Hugh',
  'male',
  '',
  '0',
  '0',
  '19947',
  '35.5',
  'C52',
  'S'],
 ['57',
  '1',
  '2',
  'Rugg, Miss. Emily',
  'female',
  '21',
  '0',
  '0',
  'C.A. 31026',
  '10.5',
  '',
  'S'],
 ['58',
  '0',
  '3',
  'Novel, Mr. Mansouer',
  'male',
  '28.5',
  '0',
  '0',
  '2697',
  '7.2292',
  '',
  'C'],
 ['59',
  '1',
  '2',
  'West, Miss. Constance Mirium',
  'female',
  '5',
  '1',
  '2',
  'C.A. 34651',
  '27.75',
  '',
  'S'],
 ['60',
  '0',
  '3',
  'Goodwin, Master. William Frederick',
  'male',
  '11',
  '5',
  '2',
  'CA 2144',
  '46.9',
  '',
  'S'],
 ['61',
  '0',
  '3',
  'Sirayanian, Mr. Orsen',
  'male',
  '22',
  '0',
  '0',
  '2669',
  '7.2292',
  '',
  'C'],
 ['62',
  '1',
  '1',
  'Icard, Miss. Amelie',
  'female',
  '38',
  '0',
  '0',
  '113572',
  '80',
  'B28',
  ''],
 ['63',
  '0',
  '1',
  'Harris, Mr. Henry Birkhardt',
  'male',
  '45',
  '1',
  '0',
  '36973',
  '83.475',
  'C83',
  'S'],
 ['64',
  '0',
  '3',
  'Skoog, Master. Harald',
  'male',
  '4',
  '3',
  '2',
  '347088',
  '27.9',
  '',
  'S'],
 ['65',
  '0',
  '1',
  'Stewart, Mr. Albert A',
  'male',
  '',
  '0',
  '0',
  'PC 17605',
  '27.7208',
  '',
  'C'],
 ['66',
  '1',
  '3',
  'Moubarek, Master. Gerios',
  'male',
  '',
  '1',
  '1',
  '2661',
  '15.2458',
  '',
  'C'],
 ['67',
  '1',
  '2',
  'Nye, Mrs. (Elizabeth Ramell)',
  'female',
  '29',
  '0',
  '0',
  'C.A. 29395',
  '10.5',
  'F33',
  'S'],
 ['68',
  '0',
  '3',
  'Crease, Mr. Ernest James',
  'male',
  '19',
  '0',
  '0',
  'S.P. 3464',
  '8.1583',
  '',
  'S'],
 ['69',
  '1',
  '3',
  'Andersson, Miss. Erna Alexandra',
  'female',
  '17',
  '4',
  '2',
  '3101281',
  '7.925',
  '',
  'S'],
 ['70',
  '0',
  '3',
  'Kink, Mr. Vincenz',
  'male',
  '26',
  '2',
  '0',
  '315151',
  '8.6625',
  '',
  'S'],
 ['71',
  '0',
  '2',
  'Jenkin, Mr. Stephen Curnow',
  'male',
  '32',
  '0',
  '0',
  'C.A. 33111',
  '10.5',
  '',
  'S'],
 ['72',
  '0',
  '3',
  'Goodwin, Miss. Lillian Amy',
  'female',
  '16',
  '5',
  '2',
  'CA 2144',
  '46.9',
  '',
  'S'],
 ['73',
  '0',
  '2',
  'Hood, Mr. Ambrose Jr',
  'male',
  '21',
  '0',
  '0',
  'S.O.C. 14879',
  '73.5',
  '',
  'S'],
 ['74',
  '0',
  '3',
  'Chronopoulos, Mr. Apostolos',
  'male',
  '26',
  '1',
  '0',
  '2680',
  '14.4542',
  '',
  'C'],
 ['75',
  '1',
  '3',
  'Bing, Mr. Lee',
  'male',
  '32',
  '0',
  '0',
  '1601',
  '56.4958',
  '',
  'S'],
 ['76',
  '0',
  '3',
  'Moen, Mr. Sigurd Hansen',
  'male',
  '25',
  '0',
  '0',
  '348123',
  '7.65',
  'F G73',
  'S'],
 ['77',
  '0',
  '3',
  'Staneff, Mr. Ivan',
  'male',
  '',
  '0',
  '0',
  '349208',
  '7.8958',
  '',
  'S'],
 ['78',
  '0',
  '3',
  'Moutal, Mr. Rahamin Haim',
  'male',
  '',
  '0',
  '0',
  '374746',
  '8.05',
  '',
  'S'],
 ['79',
  '1',
  '2',
  'Caldwell, Master. Alden Gates',
  'male',
  '0.83',
  '0',
  '2',
  '248738',
  '29',
  '',
  'S'],
 ['80',
  '1',
  '3',
  'Dowdell, Miss. Elizabeth',
  'female',
  '30',
  '0',
  '0',
  '364516',
  '12.475',
  '',
  'S'],
 ['81',
  '0',
  '3',
  'Waelens, Mr. Achille',
  'male',
  '22',
  '0',
  '0',
  '345767',
  '9',
  '',
  'S'],
 ['82',
  '1',
  '3',
  'Sheerlinck, Mr. Jan Baptist',
  'male',
  '29',
  '0',
  '0',
  '345779',
  '9.5',
  '',
  'S'],
 ['83',
  '1',
  '3',
  'McDermott, Miss. Brigdet Delia',
  'female',
  '',
  '0',
  '0',
  '330932',
  '7.7875',
  '',
  'Q'],
 ['84',
  '0',
  '1',
  'Carrau, Mr. Francisco M',
  'male',
  '28',
  '0',
  '0',
  '113059',
  '47.1',
  '',
  'S'],
 ['85',
  '1',
  '2',
  'Ilett, Miss. Bertha',
  'female',
  '17',
  '0',
  '0',
  'SO/C 14885',
  '10.5',
  '',
  'S'],
 ['86',
  '1',
  '3',
  'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
  'female',
  '33',
  '3',
  '0',
  '3101278',
  '15.85',
  '',
  'S'],
 ['87',
  '0',
  '3',
  'Ford, Mr. William Neal',
  'male',
  '16',
  '1',
  '3',
  'W./C. 6608',
  '34.375',
  '',
  'S'],
 ['88',
  '0',
  '3',
  'Slocovski, Mr. Selman Francis',
  'male',
  '',
  '0',
  '0',
  'SOTON/OQ 392086',
  '8.05',
  '',
  'S'],
 ['89',
  '1',
  '1',
  'Fortune, Miss. Mabel Helen',
  'female',
  '23',
  '3',
  '2',
  '19950',
  '263',
  'C23 C25 C27',
  'S'],
 ['90',
  '0',
  '3',
  'Celotti, Mr. Francesco',
  'male',
  '24',
  '0',
  '0',
  '343275',
  '8.05',
  '',
  'S'],
 ['91',
  '0',
  '3',
  'Christmann, Mr. Emil',
  'male',
  '29',
  '0',
  '0',
  '343276',
  '8.05',
  '',
  'S'],
 ['92',
  '0',
  '3',
  'Andreasson, Mr. Paul Edvin',
  'male',
  '20',
  '0',
  '0',
  '347466',
  '7.8542',
  '',
  'S'],
 ['93',
  '0',
  '1',
  'Chaffee, Mr. Herbert Fuller',
  'male',
  '46',
  '1',
  '0',
  'W.E.P. 5734',
  '61.175',
  'E31',
  'S'],
 ['94',
  '0',
  '3',
  'Dean, Mr. Bertram Frank',
  'male',
  '26',
  '1',
  '2',
  'C.A. 2315',
  '20.575',
  '',
  'S'],
 ['95',
  '0',
  '3',
  'Coxon, Mr. Daniel',
  'male',
  '59',
  '0',
  '0',
  '364500',
  '7.25',
  '',
  'S'],
 ['96',
  '0',
  '3',
  'Shorney, Mr. Charles Joseph',
  'male',
  '',
  '0',
  '0',
  '374910',
  '8.05',
  '',
  'S'],
 ['97',
  '0',
  '1',
  'Goldschmidt, Mr. George B',
  'male',
  '71',
  '0',
  '0',
  'PC 17754',
  '34.6542',
  'A5',
  'C'],
 ['98',
  '1',
  '1',
  'Greenfield, Mr. William Bertram',
  'male',
  '23',
  '0',
  '1',
  'PC 17759',
  '63.3583',
  'D10 D12',
  'C'],
 ['99',
  '1',
  '2',
  'Doling, Mrs. John T (Ada Julia Bone)',
  'female',
  '34',
  '0',
  '1',
  '231919',
  '23',
  '',
  'S'],
 ['100',
  '0',
  '2',
  'Kantor, Mr. Sinai',
  'male',
  '34',
  '1',
  '0',
  '244367',
  '26',
  '',
  'S'],
 ['101',
  '0',
  '3',
  'Petranec, Miss. Matilda',
  'female',
  '28',
  '0',
  '0',
  '349245',
  '7.8958',
  '',
  'S'],
 ['102',
  '0',
  '3',
  'Petroff, Mr. Pastcho ("Pentcho")',
  'male',
  '',
  '0',
  '0',
  '349215',
  '7.8958',
  '',
  'S'],
 ['103',
  '0',
  '1',
  'White, Mr. Richard Frasar',
  'male',
  '21',
  '0',
  '1',
  '35281',
  '77.2875',
  'D26',
  'S'],
 ['104',
  '0',
  '3',
  'Johansson, Mr. Gustaf Joel',
  'male',
  '33',
  '0',
  '0',
  '7540',
  '8.6542',
  '',
  'S'],
 ['105',
  '0',
  '3',
  'Gustafsson, Mr. Anders Vilhelm',
  'male',
  '37',
  '2',
  '0',
  '3101276',
  '7.925',
  '',
  'S'],
 ['106',
  '0',
  '3',
  'Mionoff, Mr. Stoytcho',
  'male',
  '28',
  '0',
  '0',
  '349207',
  '7.8958',
  '',
  'S'],
 ['107',
  '1',
  '3',
  'Salkjelsvik, Miss. Anna Kristine',
  'female',
  '21',
  '0',
  '0',
  '343120',
  '7.65',
  '',
  'S'],
 ['108',
  '1',
  '3',
  'Moss, Mr. Albert Johan',
  'male',
  '',
  '0',
  '0',
  '312991',
  '7.775',
  '',
  'S'],
 ['109',
  '0',
  '3',
  'Rekic, Mr. Tido',
  'male',
  '38',
  '0',
  '0',
  '349249',
  '7.8958',
  '',
  'S'],
 ['110',
  '1',
  '3',
  'Moran, Miss. Bertha',
  'female',
  '',
  '1',
  '0',
  '371110',
  '24.15',
  '',
  'Q'],
 ['111',
  '0',
  '1',
  'Porter, Mr. Walter Chamberlain',
  'male',
  '47',
  '0',
  '0',
  '110465',
  '52',
  'C110',
  'S'],
 ['112',
  '0',
  '3',
  'Zabour, Miss. Hileni',
  'female',
  '14.5',
  '1',
  '0',
  '2665',
  '14.4542',
  '',
  'C'],
 ['113',
  '0',
  '3',
  'Barton, Mr. David John',
  'male',
  '22',
  '0',
  '0',
  '324669',
  '8.05',
  '',
  'S'],
 ['114',
  '0',
  '3',
  'Jussila, Miss. Katriina',
  'female',
  '20',
  '1',
  '0',
  '4136',
  '9.825',
  '',
  'S'],
 ['115',
  '0',
  '3',
  'Attalah, Miss. Malake',
  'female',
  '17',
  '0',
  '0',
  '2627',
  '14.4583',
  '',
  'C'],
 ['116',
  '0',
  '3',
  'Pekoniemi, Mr. Edvard',
  'male',
  '21',
  '0',
  '0',
  'STON/O 2. 3101294',
  '7.925',
  '',
  'S'],
 ['117',
  '0',
  '3',
  'Connors, Mr. Patrick',
  'male',
  '70.5',
  '0',
  '0',
  '370369',
  '7.75',
  '',
  'Q'],
 ['118',
  '0',
  '2',
  'Turpin, Mr. William John Robert',
  'male',
  '29',
  '1',
  '0',
  '11668',
  '21',
  '',
  'S'],
 ['119',
  '0',
  '1',
  'Baxter, Mr. Quigg Edmond',
  'male',
  '24',
  '0',
  '1',
  'PC 17558',
  '247.5208',
  'B58 B60',
  'C'],
 ['120',
  '0',
  '3',
  'Andersson, Miss. Ellis Anna Maria',
  'female',
  '2',
  '4',
  '2',
  '347082',
  '31.275',
  '',
  'S'],
 ['121',
  '0',
  '2',
  'Hickman, Mr. Stanley George',
  'male',
  '21',
  '2',
  '0',
  'S.O.C. 14879',
  '73.5',
  '',
  'S'],
 ['122',
  '0',
  '3',
  'Moore, Mr. Leonard Charles',
  'male',
  '',
  '0',
  '0',
  'A4. 54510',
  '8.05',
  '',
  'S'],
 ['123',
  '0',
  '2',
  'Nasser, Mr. Nicholas',
  'male',
  '32.5',
  '1',
  '0',
  '237736',
  '30.0708',
  '',
  'C'],
 ['124',
  '1',
  '2',
  'Webber, Miss. Susan',
  'female',
  '32.5',
  '0',
  '0',
  '27267',
  '13',
  'E101',
  'S'],
 ['125',
  '0',
  '1',
  'White, Mr. Percival Wayland',
  'male',
  '54',
  '0',
  '1',
  '35281',
  '77.2875',
  'D26',
  'S'],
 ['126',
  '1',
  '3',
  'Nicola-Yarred, Master. Elias',
  'male',
  '12',
  '1',
  '0',
  '2651',
  '11.2417',
  '',
  'C'],
 ['127',
  '0',
  '3',
  'McMahon, Mr. Martin',
  'male',
  '',
  '0',
  '0',
  '370372',
  '7.75',
  '',
  'Q'],
 ['128',
  '1',
  '3',
  'Madsen, Mr. Fridtjof Arne',
  'male',
  '24',
  '0',
  '0',
  'C 17369',
  '7.1417',
  '',
  'S'],
 ['129',
  '1',
  '3',
  'Peter, Miss. Anna',
  'female',
  '',
  '1',
  '1',
  '2668',
  '22.3583',
  'F E69',
  'C'],
 ['130',
  '0',
  '3',
  'Ekstrom, Mr. Johan',
  'male',
  '45',
  '0',
  '0',
  '347061',
  '6.975',
  '',
  'S'],
 ['131',
  '0',
  '3',
  'Drazenoic, Mr. Jozef',
  'male',
  '33',
  '0',
  '0',
  '349241',
  '7.8958',
  '',
  'C'],
 ['132',
  '0',
  '3',
  'Coelho, Mr. Domingos Fernandeo',
  'male',
  '20',
  '0',
  '0',
  'SOTON/O.Q. 3101307',
  '7.05',
  '',
  'S'],
 ['133',
  '0',
  '3',
  'Robins, Mrs. Alexander A (Grace Charity Laury)',
  'female',
  '47',
  '1',
  '0',
  'A/5. 3337',
  '14.5',
  '',
  'S'],
 ['134',
  '1',
  '2',
  'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
  'female',
  '29',
  '1',
  '0',
  '228414',
  '26',
  '',
  'S'],
 ['135',
  '0',
  '2',
  'Sobey, Mr. Samuel James Hayden',
  'male',
  '25',
  '0',
  '0',
  'C.A. 29178',
  '13',
  '',
  'S'],
 ['136',
  '0',
  '2',
  'Richard, Mr. Emile',
  'male',
  '23',
  '0',
  '0',
  'SC/PARIS 2133',
  '15.0458',
  '',
  'C'],
 ['137',
  '1',
  '1',
  'Newsom, Miss. Helen Monypeny',
  'female',
  '19',
  '0',
  '2',
  '11752',
  '26.2833',
  'D47',
  'S'],
 ['138',
  '0',
  '1',
  'Futrelle, Mr. Jacques Heath',
  'male',
  '37',
  '1',
  '0',
  '113803',
  '53.1',
  'C123',
  'S'],
 ['139',
  '0',
  '3',
  'Osen, Mr. Olaf Elon',
  'male',
  '16',
  '0',
  '0',
  '7534',
  '9.2167',
  '',
  'S'],
 ['140',
  '0',
  '1',
  'Giglio, Mr. Victor',
  'male',
  '24',
  '0',
  '0',
  'PC 17593',
  '79.2',
  'B86',
  'C'],
 ['141',
  '0',
  '3',
  'Boulos, Mrs. Joseph (Sultana)',
  'female',
  '',
  '0',
  '2',
  '2678',
  '15.2458',
  '',
  'C'],
 ['142',
  '1',
  '3',
  'Nysten, Miss. Anna Sofia',
  'female',
  '22',
  '0',
  '0',
  '347081',
  '7.75',
  '',
  'S'],
 ['143',
  '1',
  '3',
  'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
  'female',
  '24',
  '1',
  '0',
  'STON/O2. 3101279',
  '15.85',
  '',
  'S'],
 ['144',
  '0',
  '3',
  'Burke, Mr. Jeremiah',
  'male',
  '19',
  '0',
  '0',
  '365222',
  '6.75',
  '',
  'Q'],
 ['145',
  '0',
  '2',
  'Andrew, Mr. Edgardo Samuel',
  'male',
  '18',
  '0',
  '0',
  '231945',
  '11.5',
  '',
  'S'],
 ['146',
  '0',
  '2',
  'Nicholls, Mr. Joseph Charles',
  'male',
  '19',
  '1',
  '1',
  'C.A. 33112',
  '36.75',
  '',
  'S'],
 ['147',
  '1',
  '3',
  'Andersson, Mr. August Edvard ("Wennerstrom")',
  'male',
  '27',
  '0',
  '0',
  '350043',
  '7.7958',
  '',
  'S'],
 ['148',
  '0',
  '3',
  'Ford, Miss. Robina Maggie "Ruby"',
  'female',
  '9',
  '2',
  '2',
  'W./C. 6608',
  '34.375',
  '',
  'S'],
 ['149',
  '0',
  '2',
  'Navratil, Mr. Michel ("Louis M Hoffman")',
  'male',
  '36.5',
  '0',
  '2',
  '230080',
  '26',
  'F2',
  'S'],
 ['150',
  '0',
  '2',
  'Byles, Rev. Thomas Roussel Davids',
  'male',
  '42',
  '0',
  '0',
  '244310',
  '13',
  '',
  'S'],
 ['151',
  '0',
  '2',
  'Bateman, Rev. Robert James',
  'male',
  '51',
  '0',
  '0',
  'S.O.P. 1166',
  '12.525',
  '',
  'S'],
 ['152',
  '1',
  '1',
  'Pears, Mrs. Thomas (Edith Wearne)',
  'female',
  '22',
  '1',
  '0',
  '113776',
  '66.6',
  'C2',
  'S'],
 ['153',
  '0',
  '3',
  'Meo, Mr. Alfonzo',
  'male',
  '55.5',
  '0',
  '0',
  'A.5. 11206',
  '8.05',
  '',
  'S'],
 ['154',
  '0',
  '3',
  'van Billiard, Mr. Austin Blyler',
  'male',
  '40.5',
  '0',
  '2',
  'A/5. 851',
  '14.5',
  '',
  'S'],
 ['155',
  '0',
  '3',
  'Olsen, Mr. Ole Martin',
  'male',
  '',
  '0',
  '0',
  'Fa 265302',
  '7.3125',
  '',
  'S'],
 ['156',
  '0',
  '1',
  'Williams, Mr. Charles Duane',
  'male',
  '51',
  '0',
  '1',
  'PC 17597',
  '61.3792',
  '',
  'C'],
 ['157',
  '1',
  '3',
  'Gilnagh, Miss. Katherine "Katie"',
  'female',
  '16',
  '0',
  '0',
  '35851',
  '7.7333',
  '',
  'Q'],
 ['158',
  '0',
  '3',
  'Corn, Mr. Harry',
  'male',
  '30',
  '0',
  '0',
  'SOTON/OQ 392090',
  '8.05',
  '',
  'S'],

In [56]:
import pandas as pd

pd_train = pd.read_csv("train.csv", header=0)

In [57]:
pd_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [76]:
len(pd_train)

204

In [59]:
#convert male and female to 0 and 1

pd_train["sex_n"] = pd_train["Sex"].apply(lambda x: 1 if x == 'male' else 0)
pd_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,sex_n
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,1
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,1
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,0
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,0
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,1
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,1
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,0
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,0
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,1
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,1
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,0
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,0
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S,1
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S,1
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q,0
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,1
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S,0
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S,0
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,1
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,1
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,0
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S,1
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,0
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,0
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S,1
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S,0
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C,0
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,1
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,1
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S,1
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S,1
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,0
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,1
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S,1
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,0
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,0
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S,1
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S,1
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,1
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,0
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,0
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S,1
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S,0
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,1
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,1
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,0
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1

In [102]:
# Fill the NaN for Age with Mean

pd_train["Age"] = pd_train["Age"].fillna(pd_train["Age"].mean())

# Fill Nan of Fare
pd_train["Fare"] = pd_train["Fare"].fillna(pd_train["Fare"].mean())

d:\programfiles\python\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
d:\programfiles\python\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [103]:
pd_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,sex_n,child
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,0,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,E46,S,1,0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.000000,1,1,PP 9549,16.7000,G6,S,0,1
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.000000,0,0,113783,26.5500,C103,S,0,0
21,22,1,2,"Beesley, Mr. Lawrence",male,34.000000,0,0,248698,13.0000,D56,S,1,0
23,24,1,1,"Sloper, Mr. William Thompson",male,28.000000,0,0,113788,35.5000,A6,S,1,0
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.000000,3,2,19950,263.0000,C23 C25 C27,S,1,0
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,29.699118,1,0,PC 17569,146.5208,B78,C,0,0
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.000000,1,0,PC 17572,76.7292,D33,C,0,0
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.000000,0,1,113509,61.9792,B30,C,1,0
55,56,1,1,"Woolner, Mr. Hugh",male,29.699118,0,0,19947,35.5000,C52,S,1,0
61,62,1,1,"Icard, Miss. Amelie",female,38.000000,0,0,113572,80.0000,B28,S,0,0
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.000000,1,0,36973,83.4750,C83,S,1,0
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.000000,0,0,C.A. 29395,10.5000,F33,S,0,0
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.000000,0,0,348123,7.6500,F G73,S,1,0
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.000000,3,2,19950,263.0000,C23 C25 C27,S,0,0
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.000000,1,0,W.E.P. 5734,61.1750,E31,S,1,0
96,97,0,1,"Goldschmidt, Mr. George B",male,71.000000,0,0,PC 17754,34.6542,A5,C,1,0
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.000000,0,1,PC 17759,63.3583,D10 D12,C,1,0
102,103,0,1,"White, Mr. Richard Frasar",male,21.000000,0,1,35281,77.2875,D26,S,1,0
110,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.000000,0,0,110465,52.0000,C110,S,1,0
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.000000,0,1,PC 17558,247.5208,B58 B60,C,1,0
123,124,1,2,"Webber, Miss. Susan",female,32.500000,0,0,27267,13.0000,E101,S,0,0
124,125,0,1,"White, Mr. Percival Wayland",male,54.000000,0,1,35281,77.2875,D26,S,1,0
128,129,1,3,"Peter, Miss. Anna",female,29.699118,1,1,2668,22.3583,F E69,C,0,0
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.000000,0,2,11752,26.2833,D47,S,0,0
137,138,0,1,"Futrelle, Mr. Jacques Heath",male,37.000000,1,0,113803,53.1000,C123,S,1,0
139,140,0,1,"Giglio, Mr. Victor",male,24.000000,0,0,PC 17593,79.2000,B86,C,1,0
148,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.500000,0,2,230080,26.0000,F2,S,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,752,1,3,"Moor, Master. Meier",male,6.000000,0,1,392096,12.4750,E121,S,1,1
759,760,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.000000,0,0,110152,86.5000,B77,S,0,0
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.000000,1,2,113760,120.0000,B96 B98,S,0,0
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.000000,1,0,13502,77.9583,D11,S,0,0
772,773,0,2,"Mack, Mrs. (Mary)",female,57.000000,0,0,S.O./P.P. 3,10.5000,E77,S,0,0
776,777,0,3,"Tobin, Mr. Roger",male,29.699118,0,0,383121,7.7500,F38,Q,1,0
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.000000,0,1,24160,211.3375,B3,S,0,0
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.000000,1,0,17474,57.0000,B20,S,0,0
782,783,0,1,"Long, Mr. Milton Clyde",male,29.000000,0,0,113501,30.0000,D6,S,1,0
789,790,0,1,"Guggenheim, Mr. Benjamin",male,46.000000,0,0,PC 17593,79.2000,B82 B84,C,1,0
796,797,1,1,"Leader, Dr. Alice (Farnham)",female,49.000000,0,0,17465,25.9292,D17,S,0,0
802,803,1,1,"Carter, Master. William Thornton II",male,11.000000,1,2,113760,120.0000,B96 B98,S,1,0
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.000000,0,0,112050,0.0000,A36,S,1,0
809,810,1,1,"Chambers, Mrs. Norman Campbell (Bertha Griggs)",female,33.000000,1,0,113806,53.1000,E8,S,0,0
815,816,0,1,"Fry, Mr. Richard",male,29.699118,0,0,112058,0.0000,B102,S,1,0
820,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.000000,1,1,12749,93.5000,B69,S,0,0
823,824,1,3,"Moor, Mrs. (Beila)",female,27.000000,0,1,392096,12.4750,E121,S,0,0
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.000000,0,0,113572,80.0000,B28,S,0,0
835,836,1,1,"Compton, Miss. Sara Rebecca",female,39.000000,1,1,PC 17756,83.1583,E49,C,0,0
839,840,1,1,"Marechal, Mr. Pierre",male,29.699118,0,0,11774,29.7000,C47,C,1,0
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,29.699118,1,0,17453,89.1042,C92,C,0,0
853,854,1,1,"Lines, Miss. Mary Conover",female,16.000000,0,1,PC 17592,39.4000,D28,S,0,0
857,858,1,1,"Daly, Mr. Peter Denis",male,51.000000,0,0,113055,26.5500,E17,S,1,0
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.000000,0,0,17466,25.9292,D17,S,0,0
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.000000,0,0,PC 17590,50.4958,A24,S,1,0
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.000000,1,1,11751,52.5542,D35,S,0,0
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.000000,0,0,695,5.0000,B51 B53 B55,S,1,0
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.000000,0,1,11767,83.1583,C50,C,0,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,0,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,1,0

In [104]:
# adding Child Column
pd_train['child'] = pd_train['Age'].apply(lambda x: 1 if x <= 8 else 0)
pd_train

d:\programfiles\python\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,sex_n,child
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,0,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,E46,S,1,0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.000000,1,1,PP 9549,16.7000,G6,S,0,1
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.000000,0,0,113783,26.5500,C103,S,0,0
21,22,1,2,"Beesley, Mr. Lawrence",male,34.000000,0,0,248698,13.0000,D56,S,1,0
23,24,1,1,"Sloper, Mr. William Thompson",male,28.000000,0,0,113788,35.5000,A6,S,1,0
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.000000,3,2,19950,263.0000,C23 C25 C27,S,1,0
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,29.699118,1,0,PC 17569,146.5208,B78,C,0,0
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.000000,1,0,PC 17572,76.7292,D33,C,0,0
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.000000,0,1,113509,61.9792,B30,C,1,0
55,56,1,1,"Woolner, Mr. Hugh",male,29.699118,0,0,19947,35.5000,C52,S,1,0
61,62,1,1,"Icard, Miss. Amelie",female,38.000000,0,0,113572,80.0000,B28,S,0,0
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.000000,1,0,36973,83.4750,C83,S,1,0
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.000000,0,0,C.A. 29395,10.5000,F33,S,0,0
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.000000,0,0,348123,7.6500,F G73,S,1,0
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.000000,3,2,19950,263.0000,C23 C25 C27,S,0,0
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.000000,1,0,W.E.P. 5734,61.1750,E31,S,1,0
96,97,0,1,"Goldschmidt, Mr. George B",male,71.000000,0,0,PC 17754,34.6542,A5,C,1,0
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.000000,0,1,PC 17759,63.3583,D10 D12,C,1,0
102,103,0,1,"White, Mr. Richard Frasar",male,21.000000,0,1,35281,77.2875,D26,S,1,0
110,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.000000,0,0,110465,52.0000,C110,S,1,0
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.000000,0,1,PC 17558,247.5208,B58 B60,C,1,0
123,124,1,2,"Webber, Miss. Susan",female,32.500000,0,0,27267,13.0000,E101,S,0,0
124,125,0,1,"White, Mr. Percival Wayland",male,54.000000,0,1,35281,77.2875,D26,S,1,0
128,129,1,3,"Peter, Miss. Anna",female,29.699118,1,1,2668,22.3583,F E69,C,0,0
136,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.000000,0,2,11752,26.2833,D47,S,0,0
137,138,0,1,"Futrelle, Mr. Jacques Heath",male,37.000000,1,0,113803,53.1000,C123,S,1,0
139,140,0,1,"Giglio, Mr. Victor",male,24.000000,0,0,PC 17593,79.2000,B86,C,1,0
148,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.500000,0,2,230080,26.0000,F2,S,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,752,1,3,"Moor, Master. Meier",male,6.000000,0,1,392096,12.4750,E121,S,1,1
759,760,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.000000,0,0,110152,86.5000,B77,S,0,0
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.000000,1,2,113760,120.0000,B96 B98,S,0,0
765,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.000000,1,0,13502,77.9583,D11,S,0,0
772,773,0,2,"Mack, Mrs. (Mary)",female,57.000000,0,0,S.O./P.P. 3,10.5000,E77,S,0,0
776,777,0,3,"Tobin, Mr. Roger",male,29.699118,0,0,383121,7.7500,F38,Q,1,0
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.000000,0,1,24160,211.3375,B3,S,0,0
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.000000,1,0,17474,57.0000,B20,S,0,0
782,783,0,1,"Long, Mr. Milton Clyde",male,29.000000,0,0,113501,30.0000,D6,S,1,0
789,790,0,1,"Guggenheim, Mr. Benjamin",male,46.000000,0,0,PC 17593,79.2000,B82 B84,C,1,0
796,797,1,1,"Leader, Dr. Alice (Farnham)",female,49.000000,0,0,17465,25.9292,D17,S,0,0
802,803,1,1,"Carter, Master. William Thornton II",male,11.000000,1,2,113760,120.0000,B96 B98,S,1,0
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.000000,0,0,112050,0.0000,A36,S,1,0
809,810,1,1,"Chambers, Mrs. Norman Campbell (Bertha Griggs)",female,33.000000,1,0,113806,53.1000,E8,S,0,0
815,816,0,1,"Fry, Mr. Richard",male,29.699118,0,0,112058,0.0000,B102,S,1,0
820,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.000000,1,1,12749,93.5000,B69,S,0,0
823,824,1,3,"Moor, Mrs. (Beila)",female,27.000000,0,1,392096,12.4750,E121,S,0,0
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.000000,0,0,113572,80.0000,B28,S,0,0
835,836,1,1,"Compton, Miss. Sara Rebecca",female,39.000000,1,1,PC 17756,83.1583,E49,C,0,0
839,840,1,1,"Marechal, Mr. Pierre",male,29.699118,0,0,11774,29.7000,C47,C,1,0
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,29.699118,1,0,17453,89.1042,C92,C,0,0
853,854,1,1,"Lines, Miss. Mary Conover",female,16.000000,0,1,PC 17592,39.4000,D28,S,0,0
857,858,1,1,"Daly, Mr. Peter Denis",male,51.000000,0,0,113055,26.5500,E17,S,1,0
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.000000,0,0,17466,25.9292,D17,S,0,0
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.000000,0,0,PC 17590,50.4958,A24,S,1,0
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.000000,1,1,11751,52.5542,D35,S,0,0
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.000000,0,0,695,5.0000,B51 B53 B55,S,1,0
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.000000,0,1,11767,83.1583,C50,C,0,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,0,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,1,0

In [105]:
pd_train[pd_train['child'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,sex_n,child
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S,0,1
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,1,1
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S,1,1
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,347054,10.4625,G6,S,0,1
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,0,1
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,1,1
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S,1,1
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S,1,1
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S,0,1
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S,1,1

In [106]:
pd_train.Pclass.unique()

array([1, 3, 2], dtype=int64)

In [107]:

pd_train["Embarked"] = pd_train["Embarked"].fillna('S')
pd_train.Embarked.unique()

d:\programfiles\python\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

array(['C', 'S', 'Q'], dtype=object)

In [108]:
pd_train = pd_train.dropna(how='any', axis=0)

In [109]:
# Features 

CATEGORICAL_COLUMNS = ["Pclass", "Sex", "Embarked"]
CONTINUOUS_COLUMNS = ["Age", "Fare", "SibSp"]

def input_fn(df):
  
    #Creates a dictionary mapping from each categorical feature column name (k)
    # to the values of that column stored in a tf.SparseTensor.
    categorical_cols = {k: tf.SparseTensor(
      indices=[[i, 0] for i in range(df[k].size)],
      values=df[k].values,
      dense_shape=[df[k].size, 1])
                      for k in CATEGORICAL_COLUMNS}
    
    continuous_cols = {k: tf.constant(df[k].values)
                     for k in CONTINUOUS_COLUMNS}  
    # Merges the two dictionaries into one.
    feature_cols = dict(continuous_cols.items() | categorical_cols.items())
    # Converts the label column into a constant Tensor.
    label = tf.constant(df['Survived'].values)
    # Returns the feature columns and the label.
    return feature_cols, label

In [126]:
#Feature Engineering
#Categorical Columns
gender   = tf.contrib.layers.sparse_column_with_keys(column_name="Sex", keys=["female", "male"])

embarked = tf.contrib.layers.sparse_column_with_keys(column_name="Embarked", keys=["S", "C", "Q"])

#Continuous Columns that I need to make into Bins
#fare = tf.contrib.layers.sparse_column_with_hash_bucket("Fare", hash_bucket_size=100)

# Regular value columns
sibsp = tf.contrib.layers.real_valued_column("SibSp")
age = tf.contrib.layers.real_valued_column("Age")
fare = tf.contrib.layers.real_valued_column("Fare")
pclass_v = tf.contrib.layers.real_valued_column("Fare")

#Bin the age
age_buckets = tf.contrib.layers.bucketized_column(age, boundaries=[8, 25, 30, 35, 40, 45, 50, 55, 60, 65])
pclass   = tf.contrib.layers.bucketized_column(pclass_v, boundaries=[1,2,2])

# Adding crossed Columns 
gender_x_pclass = tf.contrib.layers.crossed_column([gender, pclass], hash_bucket_size=int(1e4))
age_buckets_x_pclass = tf.contrib.layers.crossed_column([age_buckets, pclass], hash_bucket_size=int(1e4))
age_buckets_x_gender = tf.contrib.layers.crossed_column([age_buckets, gender], hash_bucket_size=int(1e4))

In [127]:
#Training the model
m = tf.contrib.learn.LinearClassifier(feature_columns=[
  gender, pclass, embarked, fare, sibsp, age_buckets, gender_x_pclass,
  age_buckets_x_pclass, age_buckets_x_gender])

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_environment': 'local', '_task_id': 0, '_master': '', '_tf_random_seed': None, '_evaluation_master': '', '_is_chief': True, '_save_summary_steps': 100, '_model_dir': None, '_keep_checkpoint_max': 5, '_task_type': None, '_num_ps_replicas': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001F0B948FD30>, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_num_worker_replicas': 0}
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\dushs\AppData\Local\Temp\tmpw9fi9lsd

In [131]:
# Training Test Split
import numpy as np
msk = np.random.rand(len(pd_train)) < 0.8

train = pd_train[msk]
test  = pd_train[~msk]

print(len(pd_train))
print(len(train))
print(len(test))

def train_input_fn():
  return input_fn(train)

def eval_input_fn():
  return input_fn(test)

204
170
34

In [132]:
#model fitting
m.fit(input_fn=train_input_fn, steps=200)

WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:615: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from C:\Users\dushs\AppData\Local\Temp\tmpw9fi9lsd\model.ckpt-200
INFO:tensorflow:Saving checkpoints for 201 into C:\Users\dushs\AppData\Local\Temp\tmpw9fi9lsd\model.ckpt.
INFO:tensorflow:step = 201, loss = 0.394538
INFO:tensorflow:global_step/sec: 54.1511
INFO:tensorflow:step = 301, loss = 0.373545 (1.849 sec)
INFO:tensorflow:Saving checkpoints for 400 into C:\Users\dushs\AppData\Local\Temp\tmpw9fi9lsd\model.ckpt.
INFO:tensorflow:Loss for final step: 0.36473.

LinearClassifier(params={'gradient_clip_norm': None, 'feature_columns': [_SparseColumnKeys(column_name='Sex', is_integerized=False, bucket_size=None, lookup_config=_SparseIdLookupConfig(vocabulary_file=None, keys=('female', 'male'), num_oov_buckets=0, vocab_size=2, default_value=-1), combiner='sum', dtype=tf.string), _BucketizedColumn(source_column=_RealValuedColumn(column_name='Fare', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), boundaries=(1, 2)), _SparseColumnKeys(column_name='Embarked', is_integerized=False, bucket_size=None, lookup_config=_SparseIdLookupConfig(vocabulary_file=None, keys=('S', 'C', 'Q'), num_oov_buckets=0, vocab_size=3, default_value=-1), combiner='sum', dtype=tf.string), _RealValuedColumn(column_name='Fare', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _RealValuedColumn(column_name='SibSp', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), _BucketizedColumn(source_column=_RealValuedColumn(column_name='Age', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), boundaries=(8, 25, 30, 35, 40, 45, 50, 55, 60, 65)), _CrossedColumn(columns=(_BucketizedColumn(source_column=_RealValuedColumn(column_name='Fare', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), boundaries=(1, 2)), _SparseColumnKeys(column_name='Sex', is_integerized=False, bucket_size=None, lookup_config=_SparseIdLookupConfig(vocabulary_file=None, keys=('female', 'male'), num_oov_buckets=0, vocab_size=2, default_value=-1), combiner='sum', dtype=tf.string)), hash_bucket_size=10000, hash_key=None, combiner='sum', ckpt_to_load_from=None, tensor_name_in_ckpt=None), _CrossedColumn(columns=(_BucketizedColumn(source_column=_RealValuedColumn(column_name='Age', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), boundaries=(8, 25, 30, 35, 40, 45, 50, 55, 60, 65)), _BucketizedColumn(source_column=_RealValuedColumn(column_name='Fare', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), boundaries=(1, 2))), hash_bucket_size=10000, hash_key=None, combiner='sum', ckpt_to_load_from=None, tensor_name_in_ckpt=None), _CrossedColumn(columns=(_BucketizedColumn(source_column=_RealValuedColumn(column_name='Age', dimension=1, default_value=None, dtype=tf.float32, normalizer=None), boundaries=(8, 25, 30, 35, 40, 45, 50, 55, 60, 65)), _SparseColumnKeys(column_name='Sex', is_integerized=False, bucket_size=None, lookup_config=_SparseIdLookupConfig(vocabulary_file=None, keys=('female', 'male'), num_oov_buckets=0, vocab_size=2, default_value=-1), combiner='sum', dtype=tf.string)), hash_bucket_size=10000, hash_key=None, combiner='sum', ckpt_to_load_from=None, tensor_name_in_ckpt=None)], 'joint_weights': False, 'head': <tensorflow.contrib.learn.python.learn.estimators.head._BinaryLogisticHead object at 0x000001F0B948F208>, 'optimizer': None})

In [133]:
results = m.evaluate(input_fn=eval_input_fn, steps=1)
for key in sorted(results):
    print("%s: %s" % (key, results[key]))

WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:615: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-06-09-18:45:29
INFO:tensorflow:Restoring parameters from C:\Users\dushs\AppData\Local\Temp\tmpw9fi9lsd\model.ckpt-400
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2017-06-09-18:45:30
INFO:tensorflow:Saving dict for global step 400: accuracy = 0.735294, accuracy/baseline_label_mean = 0.529412, accuracy/threshold_0.500000_mean = 0.735294, auc = 0.854167, global_step = 400, labels/actual_label_mean = 0.529412, labels/prediction_mean = 0.664496, loss = 0.526874, precision/positive_threshold_0.500000_mean = 0.695652, recall/positive_threshold_0.500000_mean = 0.888889
WARNING:tensorflow:Skipping summary for global_step, must be a float or np.float32.
accuracy: 0.735294
accuracy/baseline_label_mean: 0.529412
accuracy/threshold_0.500000_mean: 0.735294
auc: 0.854167
global_step: 400
labels/actual_label_mean: 0.529412
labels/prediction_mean: 0.664496
loss: 0.526874
precision/positive_threshold_0.500000_mean: 0.695652
recall/positive_threshold_0.500000_mean: 0.888889

In [137]:
pred = m.predict(input_fn=eval_input_fn)
for val in pred:
    print(val)

WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\python\util\deprecation.py:335: calling LinearClassifier.predict (from tensorflow.contrib.learn.python.learn.estimators.linear) with outputs=None is deprecated and will be removed after 2017-03-01.
Instructions for updating:
Please switch to predict_classes, or set `outputs` argument.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
INFO:tensorflow:Restoring parameters from C:\Users\dushs\AppData\Local\Temp\tmpw9fi9lsd\model.ckpt-400
1
0
1
0
0
1
0
1
0
1
0
1
0
1
1
1
0
0
0
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1

In [143]:
pd_test = pd.read_csv("test.csv", header=0)
pd_test['Survived'] = 0
pd_test["sex_n"] = pd_test["Sex"].apply(lambda x: 1 if x == 'male' else 0)
pd_test["Age"] = pd_test["Age"].fillna(pd_test["Age"].mean())
pd_test["Fare"] = pd_test["Fare"].fillna(pd_test["Fare"].mean())
print(pd_test)
def test_input_fn():
  return input_fn(pd_test)

pred = m.predict(input_fn=test_input_fn)
for val in pred:
    print(val)

     PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James
1            893       3                   Wilkes, Mrs. James (Ellen Needs)
2            894       2                          Myles, Mr. Thomas Francis
3            895       3                                   Wirz, Mr. Albert
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)
5            897       3                         Svensson, Mr. Johan Cervin
6            898       3                               Connolly, Miss. Kate
7            899       2                       Caldwell, Mr. Albert Francis
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)
9            901       3                            Davies, Mr. John Samuel
10           902       3                                   Ilieff, Mr. Ylio
11           903       1                         Jones, Mr. Charles Cresson
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)
13           905       2                               Howard, Mr. Benjamin
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)
16           908       2                                  Keane, Mr. Daniel
17           909       3                                  Assaf, Mr. Gerios
18           910       3                       Ilmakangas, Miss. Ida Livija
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"
20           912       1                             Rothschild, Mr. Martin
21           913       3                          Olsen, Master. Artur Karl
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)
23           915       1                    Williams, Mr. Richard Norris II
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)
25           917       3                            Robins, Mr. Alexander A
26           918       1                       Ostby, Miss. Helene Ragnhild
27           919       3                                  Daher, Mr. Shedid
28           920       1                            Brady, Mr. John Bertram
29           921       3                                  Samaan, Mr. Elias
..           ...     ...                                                ...
388         1280       3                               Canavan, Mr. Patrick
389         1281       3                        Palsson, Master. Paul Folke
390         1282       1                         Payne, Mr. Vivian Ponsonby
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)
392         1284       3                      Abbott, Master. Eugene Joseph
393         1285       2                               Gilbert, Mr. William
394         1286       3                           Kink-Heilmann, Mr. Anton
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)
396         1288       3                               Colbert, Mr. Patrick
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...
398         1290       3                     Larsson-Rondberg, Mr. Edvard A
399         1291       3                           Conlon, Mr. Thomas Henry
400         1292       1                            Bonnell, Miss. Caroline
401         1293       2                                    Gale, Mr. Harry
402         1294       1                     Gibson, Miss. Dorothy Winifred
403         1295       1                             Carrau, Mr. Jose Pedro
404         1296       1                       Frauenthal, Mr. Isaac Gerald
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"
406         1298       2                          Ware, Mr. William Jeffery
407         1299       1                         Widener, Mr. George Dunton
408         1300       3                    Riordan, Miss. Johanna Hannah""
409         1301       3                          Peacock, Miss. Treasteall
410         1302       3                             Naughton, Miss. Hannah
411         1303       1    Minahan, Mrs. William Edward (Lillian E Thorpe)
412         1304       3                     Henriksson, Miss. Jenny Lovisa
413         1305       3                                 Spector, Mr. Woolf
414         1306       1                       Oliva y Ocana, Dona. Fermina
415         1307       3                       Saether, Mr. Simon Sivertsen
416         1308       3                                Ware, Mr. Frederick
417         1309       3                           Peter, Master. Michael J

        Sex       Age  SibSp  Parch              Ticket      Fare  \
0      male  34.50000      0      0              330911    7.8292
1    female  47.00000      1      0              363272    7.0000
2      male  62.00000      0      0              240276    9.6875
3      male  27.00000      0      0              315154    8.6625
4    female  22.00000      1      1             3101298   12.2875
5      male  14.00000      0      0                7538    9.2250
6    female  30.00000      0      0              330972    7.6292
7      male  26.00000      1      1              248738   29.0000
8    female  18.00000      0      0                2657    7.2292
9      male  21.00000      2      0           A/4 48871   24.1500
10     male  30.27259      0      0              349220    7.8958
11     male  46.00000      0      0                 694   26.0000
12   female  23.00000      1      0               21228   82.2667
13     male  63.00000      1      0               24065   26.0000
14   female  47.00000      1      0         W.E.P. 5734   61.1750
15   female  24.00000      1      0       SC/PARIS 2167   27.7208
16     male  35.00000      0      0              233734   12.3500
17     male  21.00000      0      0                2692    7.2250
18   female  27.00000      1      0    STON/O2. 3101270    7.9250
19   female  45.00000      0      0                2696    7.2250
20     male  55.00000      1      0            PC 17603   59.4000
21     male   9.00000      0      1             C 17368    3.1708
22   female  30.27259      0      0            PC 17598   31.6833
23     male  21.00000      0      1            PC 17597   61.3792
24   female  48.00000      1      3            PC 17608  262.3750
25     male  50.00000      1      0           A/5. 3337   14.5000
26   female  22.00000      0      1              113509   61.9792
27     male  22.50000      0      0                2698    7.2250
28     male  41.00000      0      0              113054   30.5000
29     male  30.27259      2      0                2662   21.6792
..      ...       ...    ...    ...                 ...       ...
388    male  21.00000      0      0              364858    7.7500
389    male   6.00000      3      1              349909   21.0750
390    male  23.00000      0      0               12749   93.5000
391  female  51.00000      0      1            PC 17592   39.4000
392    male  13.00000      0      2           C.A. 2673   20.2500
393    male  47.00000      0      0          C.A. 30769   10.5000
394    male  29.00000      3      1              315153   22.0250
395  female  18.00000      1      0               13695   60.0000
396    male  24.00000      0      0              371109    7.2500
397  female  48.00000      1      1               13567   79.2000
398    male  22.00000      0      0              347065    7.7750
399    male  31.00000      0      0               21332    7.7333
400  female  30.00000      0      0               36928  164.8667
401    male  38.00000      1      0               28664   21.0000
402  female  22.00000      0      1              112378   59.4000
403    male  17.00000      0      0              113059   47.1000
404    male  43.00000      1      0               17765   27.7208
405    male  20.00000      0      0       SC/PARIS 2166   13.8625
406    male  23.00000      1      0               28666   10.5000
407    male  50.00000      1      1              113503  211.5000
408  female  30.27259      0      0              334915    7.7208
409  female   3.00000      1      1  SOTON/O.Q. 3101315   13.7750
410  female  30.27259      0      0              365237    7.7500
411  female  37.00000      1      0               19928   90.0000
412  female  28.00000      0      0              347086    7.7750
413    male  30.27259      0      0           A.5. 3236    8.0500
414  female  39.00000      0      0            PC 17758  108.9000
415    male  38.50000      0      0  SOTON/O.Q. 3101262    7.2500
416    male  30.27259      0      0              359309    8.0500
417    male  30.27259      1      1                2668   22.3583

               Cabin Embarked  Survived  sex_n
0                NaN        Q         0      1
1                NaN        S         0      0
2                NaN        Q         0      1
3                NaN        S         0      1
4                NaN        S         0      0
5                NaN        S         0      1
6                NaN        Q         0      0
7                NaN        S         0      1
8                NaN        C         0      0
9                NaN        S         0      1
10               NaN        S         0      1
11               NaN        S         0      1
12               B45        S         0      0
13               NaN        S         0      1
14               E31        S         0      0
15               NaN        C         0      0
16               NaN        Q         0      1
17               NaN        C         0      1
18               NaN        S         0      0
19               NaN        C         0      0
20               NaN        C         0      1
21               NaN        S         0      1
22               NaN        S         0      0
23               NaN        C         0      1
24   B57 B59 B63 B66        C         0      0
25               NaN        S         0      1
26               B36        C         0      0
27               NaN        C         0      1
28               A21        S         0      1
29               NaN        C         0      1
..               ...      ...       ...    ...
388              NaN        Q         0      1
389              NaN        S         0      1
390              B24        S         0      1
391              D28        S         0      0
392              NaN        S         0      1
393              NaN        S         0      1
394              NaN        S         0      1
395              C31        S         0      0
396              NaN        Q         0      1
397              B41        C         0      0
398              NaN        S         0      1
399              NaN        Q         0      1
400               C7        S         0      0
401              NaN        S         0      1
402              NaN        C         0      0
403              NaN        S         0      1
404              D40        C         0      1
405              D38        C         0      1
406              NaN        S         0      1
407              C80        C         0      1
408              NaN        Q         0      0
409              NaN        S         0      0
410              NaN        Q         0      0
411              C78        Q         0      0
412              NaN        S         0      0
413              NaN        S         0      1
414             C105        C         0      0
415              NaN        S         0      1
416              NaN        S         0      1
417              NaN        C         0      1

[418 rows x 13 columns]
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\python\util\deprecation.py:335: calling LinearClassifier.predict (from tensorflow.contrib.learn.python.learn.estimators.linear) with outputs=None is deprecated and will be removed after 2017-03-01.
Instructions for updating:
Please switch to predict_classes, or set `outputs` argument.

WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:From d:\programfiles\python\lib\site-packages\tensorflow\contrib\layers\python\layers\feature_column.py:1861: calling sparse_feature_cross (from tensorflow.contrib.layers.python.ops.sparse_feature_cross_op) with hash_key=None is deprecated and will be removed after 2016-11-20.
Instructions for updating:
The default behavior of sparse_feature_cross is changing, the default
value for hash_key will change to SPARSE_FEATURE_CROSS_DEFAULT_HASH_KEY.
From that point on sparse_feature_cross will always use FingerprintCat64
to concatenate the feature fingerprints. And the underlying
_sparse_feature_cross_op.sparse_feature_cross operation will be marked
as deprecated.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
WARNING:tensorflow:Rank of input Tensor (1) should be the same as output_rank (2) for column. Will attempt to expand dims. It is highly recommended that you resize your input, as this behavior may change.
INFO:tensorflow:Restoring parameters from C:\Users\dushs\AppData\Local\Temp\tmpw9fi9lsd\model.ckpt-400
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
1
0
0
1
1
0
0
1
1
1
0
1
0
1
1
0
0
1
1
1
0
1
1
0
1
1
1
1
1
1
0
0
0
1
1
0
1
1
1
1
0
0
0
1
1
0
1
0
1
1
1
1
0
1
1
1
0
1
1
1
1
1
1
1
1
1
0
0
1
0
1
1
1
1
1
1
1
1
1
1
0
1
0
1
1
1
0
0
0
1
0
0
0
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
0
0
1
0
1
1
0
1
0
1
1
1
0
1
0
1
1
1
1
1
0
1
1
1
0
1
1
1
1
0
1
1
0
1
1
1
1
1
1
1
1
1
1
0
0
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
0
1
1
1
0
1
1
1
1
0
0
0
1
1
1
0
1
1
1
1
1
0
1
1
0
1
0
1
1
0
1
1
1
1
0
1
1
1
0
1
0
1
1
0
1
1
0
0
1
0
0
1
0
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
0
1
1
0
0
1
0
1
0
1
1
1
1
0
1
1
0
0
0
1
1
1
1
0
1
1
0
1
1
1
1
1
0
1
0
1
1
1
1
1
0
0
0
1
1
1
0
1
1
1
0
1
1
1
1
0
1
0
0
1
1
1
1
0
0
0
0
0
1
0
1
1
0
1
0
0
0
1
1
1
1
0
1
1
1
0
1
0
1
1
1
1
1
0
1
0
1
1
0
0
0
1
0
1
1
0
1
1
1
1
0
1
1
1
1
1
1
0
1
0
1
1
1
1
0
0
1
0
0
1
1
1
1
0
0
0
1
0
1
0
0
1
1
0
1
0
0
1
1
1
0
1
0
0
1
1
1
1
1
1
1
1
0
1
1

In [144]:
pd_test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived,sex_n
0,892,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q,0,1
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S,0,0
2,894,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q,0,1
3,895,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S,0,1
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S,0,0
5,897,3,"Svensson, Mr. Johan Cervin",male,14.00000,0,0,7538,9.2250,NaN,S,0,1
6,898,3,"Connolly, Miss. Kate",female,30.00000,0,0,330972,7.6292,NaN,Q,0,0
7,899,2,"Caldwell, Mr. Albert Francis",male,26.00000,1,1,248738,29.0000,NaN,S,0,1
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00000,0,0,2657,7.2292,NaN,C,0,0
9,901,3,"Davies, Mr. John Samuel",male,21.00000,2,0,A/4 48871,24.1500,NaN,S,0,1
10,902,3,"Ilieff, Mr. Ylio",male,30.27259,0,0,349220,7.8958,NaN,S,0,1
11,903,1,"Jones, Mr. Charles Cresson",male,46.00000,0,0,694,26.0000,NaN,S,0,1
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.00000,1,0,21228,82.2667,B45,S,0,0
13,905,2,"Howard, Mr. Benjamin",male,63.00000,1,0,24065,26.0000,NaN,S,0,1
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.00000,1,0,W.E.P. 5734,61.1750,E31,S,0,0
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.00000,1,0,SC/PARIS 2167,27.7208,NaN,C,0,0
16,908,2,"Keane, Mr. Daniel",male,35.00000,0,0,233734,12.3500,NaN,Q,0,1
17,909,3,"Assaf, Mr. Gerios",male,21.00000,0,0,2692,7.2250,NaN,C,0,1
18,910,3,"Ilmakangas, Miss. Ida Livija",female,27.00000,1,0,STON/O2. 3101270,7.9250,NaN,S,0,0
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.00000,0,0,2696,7.2250,NaN,C,0,0
20,912,1,"Rothschild, Mr. Martin",male,55.00000,1,0,PC 17603,59.4000,NaN,C,0,1
21,913,3,"Olsen, Master. Artur Karl",male,9.00000,0,1,C 17368,3.1708,NaN,S,0,1
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,30.27259,0,0,PC 17598,31.6833,NaN,S,0,0
23,915,1,"Williams, Mr. Richard Norris II",male,21.00000,0,1,PC 17597,61.3792,NaN,C,0,1
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.00000,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,0,0
25,917,3,"Robins, Mr. Alexander A",male,50.00000,1,0,A/5. 3337,14.5000,NaN,S,0,1
26,918,1,"Ostby, Miss. Helene Ragnhild",female,22.00000,0,1,113509,61.9792,B36,C,0,0
27,919,3,"Daher, Mr. Shedid",male,22.50000,0,0,2698,7.2250,NaN,C,0,1
28,920,1,"Brady, Mr. John Bertram",male,41.00000,0,0,113054,30.5000,A21,S,0,1
29,921,3,"Samaan, Mr. Elias",male,30.27259,2,0,2662,21.6792,NaN,C,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,1280,3,"Canavan, Mr. Patrick",male,21.00000,0,0,364858,7.7500,NaN,Q,0,1
389,1281,3,"Palsson, Master. Paul Folke",male,6.00000,3,1,349909,21.0750,NaN,S,0,1
390,1282,1,"Payne, Mr. Vivian Ponsonby",male,23.00000,0,0,12749,93.5000,B24,S,0,1
391,1283,1,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)",female,51.00000,0,1,PC 17592,39.4000,D28,S,0,0
392,1284,3,"Abbott, Master. Eugene Joseph",male,13.00000,0,2,C.A. 2673,20.2500,NaN,S,0,1
393,1285,2,"Gilbert, Mr. William",male,47.00000,0,0,C.A. 30769,10.5000,NaN,S,0,1
394,1286,3,"Kink-Heilmann, Mr. Anton",male,29.00000,3,1,315153,22.0250,NaN,S,0,1
395,1287,1,"Smith, Mrs. Lucien Philip (Mary Eloise Hughes)",female,18.00000,1,0,13695,60.0000,C31,S,0,0
396,1288,3,"Colbert, Mr. Patrick",male,24.00000,0,0,371109,7.2500,NaN,Q,0,1
397,1289,1,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",female,48.00000,1,1,13567,79.2000,B41,C,0,0
398,1290,3,"Larsson-Rondberg, Mr. Edvard A",male,22.00000,0,0,347065,7.7750,NaN,S,0,1
399,1291,3,"Conlon, Mr. Thomas Henry",male,31.00000,0,0,21332,7.7333,NaN,Q,0,1
400,1292,1,"Bonnell, Miss. Caroline",female,30.00000,0,0,36928,164.8667,C7,S,0,0
401,1293,2,"Gale, Mr. Harry",male,38.00000,1,0,28664,21.0000,NaN,S,0,1
402,1294,1,"Gibson, Miss. Dorothy Winifred",female,22.00000,0,1,112378,59.4000,NaN,C,0,0
403,1295,1,"Carrau, Mr. Jose Pedro",male,17.00000,0,0,113059,47.1000,NaN,S,0,1
404,1296,1,"Frauenthal, Mr. Isaac Gerald",male,43.00000,1,0,17765,27.7208,D40,C,0,1
405,1297,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.00000,0,0,SC/PARIS 2166,13.8625,D38,C,0,1
406,1298,2,"Ware, Mr. William Jeffery",male,23.00000,1,0,28666,10.5000,NaN,S,0,1
407,1299,1,"Widener, Mr. George Dunton",male,50.00000,1,1,113503,211.5000,C80,C,0,1
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,30.27259,0,0,334915,7.7208,NaN,Q,0,0
409,1301,3,"Peacock, Miss. Treasteall",female,3.00000,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,0,0
410,1302,3,"Naughton, Miss. Hannah",female,30.27259,0,0,365237,7.7500,NaN,Q,0,0
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.00000,1,0,19928,90.0000,C78,Q,0,0
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.00000,0,0,347086,7.7750,NaN,S,0,0
413,1305,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S,0,1
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C,0,0
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,1
416,1308,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S,0,1
417,1309,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C,0,1